### ISSUE TITLE
DICT Checklist

### ISSUE THREAD

**Issue by yandevv** [eletroswing/bacen-simulator#19]
# Issues

- [x] start a sqlite system in infra folder #10 @eletroswing 
- [x] create a router to every DICT route @eletroswing  
- [x] develop an creating route of pix key #5 @eletroswing 
- [x] check the existence of keys with batches #7 
- [x] develop an fetch(get) route of pix key w/ params #4 @yandevv 
- [x] develop an deleting route of pix key w/ params #57
- [x] develop an updating route of pix key w/ params #6 @yandevv 

# Backlog

- [ ] develop devolution systems #8 
- [x] fix zod zeros parsing #49
