### ISSUE TITLE
Documentation Checklist

### ISSUE THREAD

**Issue by yandevv** [eletroswing/bacen-simulator#24]
# Issues
- [x] create a relational and logic database model #23 @yandevv 
- [x] docs with swagger #38 @eletroswing 
- [ ] implement scalar ui on openapi docs #65
