### ISSUE TITLE
Kickstarting Checklist

### ISSUE THREAD

**Issue by yandevv** [eletroswing/bacen-simulator#29]
# Issues

- [x] create repo
- [x] define techstack
- [x] install initital dependencies
- [x] create a default welcome route #30 @yandevv 
- [x] transform repo to monorepo with Turborepo #31 @yandevv 
- [x] initiate docker in the project  #40 @yandevv
